### 接口1
POST http://localhost:9090/tcu/register/register?phoneNumber=18080266036
Content-Type: application/json
Cookie: {{JSESSIONID}}

### 接口2
POST http://localhost:9090/tcu/register/register
Content-Type: application/json

{
    "phoneNumber" : "18080266036",
    "authCode": "277191"
}

### 接口3 账号校验
POST http://localhost:9090/tcu/register/username
Content-Type: application/json

{
  "username": "111"
}

### 接口4 密码校验
POST http://localhost:9090/tcu/register/password
Content-Type: application/json

{
  "password": "111"
}

### 接口5 发送email
POST http://localhost:9090/tcu/register/sendUserCode
Content-Type: application/json

{
  "email": "111"
}

### 接口6 用户信息
POST http://localhost:9090/tcu/register/userinfo
Content-Type: application/json

{
  "username": "",
  "password": "",
  "email": "",
  "imgUrl": "",
  "emailCode": ""
}

### 接口1 通过账号密码登录
POST http://localhost:9090/tcu/register/userinfo
Content-Type: application/json

{
  "userAccount" : "",
  "userPassword" : "",
  "strategyName": ""
}